package Vistas;

/**
 *
 * @author valem
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Registar = new javax.swing.JMenu();
        RegistarEscuela = new javax.swing.JMenuItem();
        RegistrarPlanEstudio = new javax.swing.JMenuItem();
        RegistarCurso = new javax.swing.JMenuItem();
        RegistarReqCo = new javax.swing.JMenuItem();
        Consultar = new javax.swing.JMenu();
        ConsultarPlanEstudio = new javax.swing.JMenuItem();
        ConsultarCursoPlan = new javax.swing.JMenuItem();
        ConsultarReq = new javax.swing.JMenuItem();
        ConsultarCo = new javax.swing.JMenuItem();
        Modificadores = new javax.swing.JMenu();
        EliminarReq = new javax.swing.JMenuItem();
        EliminarCursoPlan = new javax.swing.JMenuItem();
        EliminarCurso = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 24)); // NOI18N
        jLabel1.setText("Gestor de Planes de Estudio");
        jLabel1.setToolTipText("");

        Registar.setText("Registar");

        RegistarEscuela.setLabel("Registar Escuela");
        RegistarEscuela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarEscuelaActionPerformed(evt);
            }
        });
        Registar.add(RegistarEscuela);

        RegistrarPlanEstudio.setText("Registar Plan de estudio");
        RegistrarPlanEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrarPlanEstudioActionPerformed(evt);
            }
        });
        Registar.add(RegistrarPlanEstudio);

        RegistarCurso.setLabel("Registar Curso");
        RegistarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarCursoActionPerformed(evt);
            }
        });
        Registar.add(RegistarCurso);

        RegistarReqCo.setLabel("Registar Requisitos o Correquisitos");
        RegistarReqCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistarReqCoActionPerformed(evt);
            }
        });
        Registar.add(RegistarReqCo);

        jMenuBar1.add(Registar);

        Consultar.setText("Consultar");

        ConsultarPlanEstudio.setText("Consultar plan de estudio");
        ConsultarPlanEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarPlanEstudioActionPerformed(evt);
            }
        });
        Consultar.add(ConsultarPlanEstudio);

        ConsultarCursoPlan.setText("Conusltar cursos en plan de estudio");
        ConsultarCursoPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarCursoPlanActionPerformed(evt);
            }
        });
        Consultar.add(ConsultarCursoPlan);

        ConsultarReq.setText("Consultar requisito");
        ConsultarReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarReqActionPerformed(evt);
            }
        });
        Consultar.add(ConsultarReq);

        ConsultarCo.setText("Consulta correquisito");
        ConsultarCo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultarCoActionPerformed(evt);
            }
        });
        Consultar.add(ConsultarCo);

        jMenuBar1.add(Consultar);

        Modificadores.setText("Modificadores");

        EliminarReq.setText("Eliminar un requisito");
        EliminarReq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarReqActionPerformed(evt);
            }
        });
        Modificadores.add(EliminarReq);

        EliminarCursoPlan.setText("Eliminar curso de un plan de estudios");
        EliminarCursoPlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCursoPlanActionPerformed(evt);
            }
        });
        Modificadores.add(EliminarCursoPlan);

        EliminarCurso.setText("Eliminar curso");
        EliminarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarCursoActionPerformed(evt);
            }
        });
        Modificadores.add(EliminarCurso);

        jMenuBar1.add(Modificadores);

        jMenu1.setText("Salir");

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(jLabel1)
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarCursoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCursoPlanActionPerformed
       Controlador.ConMenu.AbrirEliminarCursoPlan();
       this.dispose();
    }//GEN-LAST:event_EliminarCursoPlanActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void RegistrarPlanEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarPlanEstudioActionPerformed
        Controlador.ConMenu.AbrirResgistroPlanEstudio();
        this.dispose();
    }//GEN-LAST:event_RegistrarPlanEstudioActionPerformed

    private void RegistarEscuelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarEscuelaActionPerformed
        Controlador.ConMenu.AbrirResgistroEscuela();
        this.dispose();
    }//GEN-LAST:event_RegistarEscuelaActionPerformed

    private void RegistarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarCursoActionPerformed
        Controlador.ConMenu.AbrirResgistroCurso();
        this.dispose();
    }//GEN-LAST:event_RegistarCursoActionPerformed

    private void RegistarReqCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistarReqCoActionPerformed
        Controlador.ConMenu.AbrirResgistroReqCo();
        this.dispose();
    }//GEN-LAST:event_RegistarReqCoActionPerformed

    private void ConsultarPlanEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarPlanEstudioActionPerformed
        Controlador.ConMenu.AbrirConsultaPlan();
        this.dispose();
    }//GEN-LAST:event_ConsultarPlanEstudioActionPerformed

    private void ConsultarCursoPlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarCursoPlanActionPerformed
        Controlador.ConMenu.AbrirConsultaCursoPlan();
        this.dispose();
    }//GEN-LAST:event_ConsultarCursoPlanActionPerformed

    private void ConsultarCoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarCoActionPerformed
        Controlador.ConMenu.AbrirConsultaCursoCo();
        this.dispose();
    }//GEN-LAST:event_ConsultarCoActionPerformed

    private void ConsultarReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultarReqActionPerformed
        Controlador.ConMenu.AbrirConsultaCursoReq();
        this.dispose();
    }//GEN-LAST:event_ConsultarReqActionPerformed

    private void EliminarReqActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarReqActionPerformed
        Controlador.ConMenu.AbrirEliminarCursoReq();
        this.dispose();
    }//GEN-LAST:event_EliminarReqActionPerformed

    private void EliminarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarCursoActionPerformed
        Controlador.ConMenu.AbrirEliminarCurso();
        this.dispose();
    }//GEN-LAST:event_EliminarCursoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Consultar;
    private javax.swing.JMenuItem ConsultarCo;
    private javax.swing.JMenuItem ConsultarCursoPlan;
    private javax.swing.JMenuItem ConsultarPlanEstudio;
    private javax.swing.JMenuItem ConsultarReq;
    private javax.swing.JMenuItem EliminarCurso;
    private javax.swing.JMenuItem EliminarCursoPlan;
    private javax.swing.JMenuItem EliminarReq;
    private javax.swing.JMenu Modificadores;
    private javax.swing.JMenu Registar;
    private javax.swing.JMenuItem RegistarCurso;
    private javax.swing.JMenuItem RegistarEscuela;
    private javax.swing.JMenuItem RegistarReqCo;
    private javax.swing.JMenuItem RegistrarPlanEstudio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    // End of variables declaration//GEN-END:variables

}
